baseurl                  = "https://robonyong.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "robonyong the website"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "robonyong.ico"
    homepage             = "home"                           # What to call the home page link
    footerText           = "robin yang's website presence"

# Metadata for Open Graph and Twitter
    description          = "robin yang's website presence"  # Max 160 characters show in search results
    images               = ["sp.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "robonyong"

[[params.mainMenu]]
    link = "about"
    text = "background"

[[params.mainMenu]]
    link = "/projects"
    text = "projects"

[imaging]
    quality = 75